module.exports = {
    querying: {
        get: 'get',
        contains: 'contains',
        within: 'within',
        root: 'root',
    },
    traversal: {
        children: 'children',
        closest: 'closest',
        eq: 'eq',
        filter: 'filter',
        find: 'find',
        first: 'first',
        last: 'last',
        next: 'next',
        nextAll: 'nextAll',
        nextUntil: 'nextUntil',
        not: 'not',
        parent: 'parent',
        parents: 'parents',
        parentsUntil: 'parentsUntil',
        prev: 'prev',
        prevAll: 'prevAll',
        prevUntil: 'prevUntil',
        siblings: 'siblings',
    },
    actions: {
        type: 'type',
        focus: 'focus',
        blur: 'blur',
        clear: 'clear',
        submit: 'submit',
        click: 'click',
        dblclick: 'dblclick',
        rightclick: 'rightclick',
        check: 'check',
        uncheck: 'uncheck',
        select: 'select',
        scrollIntoView: 'scrollIntoView',
        scrollTo: 'scrollTo',
        trigger: 'trigger',
    },
    window: {
        window: 'window',
        document: 'document',
        title: 'title',
    },
    navigation: {
        go: 'go',
        reload: 'reload',
        visit: 'visit',
    },
    assertions: {
        implicit: {
            should: 'should',
            and: 'and',
        },
        explicit: {
            expect: 'expect',
            assert: 'assert',
        },
    },
    chai: {
        bdd: {
            not: 'not',
            deep: 'deep',
            nested: 'nested',
            ordered: 'ordered',
            any: 'any',
            all: 'all',
            include: 'include',
            ok: 'ok',
            true: 'true',
            false: 'false',
            null: 'null',
            undefined: 'undefined',
            exist: 'exist',
            empty: 'empty',
            equal: 'equal',
            within: 'within',
            string: 'string',

        },
        chainable: {
            to: 'to',
            be: 'be',
            been: 'been',
            is: 'is',
            that: 'that',
            which: 'which',
            and: 'and',
            has: 'has',
            have: 'have',
            with: 'with',
            at: 'at',
            of: 'of',
            same: 'same',
        },
    },
}
